let cantina = new Cantina;
let beer1 = new Beer("Beer", "Ichnusa", "NonFiltrata", 12, 15, "Chiara");
let wine1 = new Wine("Wine", "A-Maccia", "PigatoDiUnaVolta", 12, 15, 2010, "Santo Pippo");
let wine2 = new Wine("Wine", "Patata", "Piga", 12, 15, 2010, "Santo Pippo");
cantina.addProduct(beer1);
cantina.addProduct(wine1);
cantina.addProduct(wine2);
cantina.addSubBottles("B-Ichnusa-NonFiltrata-2022-2-5", 5);
cantina.addSubBottles("W-A-Maccia-PigatoDiUnaVolta-2022-2-5", 5);
console.log(cantina.checkQuantity("B-Ichnusa-NonFiltrata-2022-2-5"));
console.log(cantina);
console.log(cantina.beers[0].code);
console.log(cantina.beers[0].price);
console.log(cantina.beers[0].insertionDate);
console.log(cantina.toString(cantina.beers[0]));
console.log(cantina.toString(cantina.wines[0]));
console.log(cantina.searchByVine("Santo Pippo"));
console.log(cantina.checkQuantityByVine("Santo Pippo"));
console.log(cantina.checkQuantityByYear(2010));
console.log(cantina.checkQuantityByBeerType("Chiara"));
cantina.checkStorage();
